### ISSUE TITLE
콜백함수의 정의 Quiz

### ISSUE THREAD

**Issue by jinseoIT** [fe-drilling/gurren-lagann#1]
아래 두가지 중 콜백함수의 정의는 무엇일까요.
```javascript
function B() {
  return 1;
}
function A (B) {
  console.log(B());
}
```
1. 함수를 인자로 사용하는 함수. A
2. 다른 함수의 인자로써 이용되는 함수. B

둘중 어떤게 콜백함수일까요?

**Comment by yunseorim1116** [comment]
https://developer.mozilla.org/ko/docs/Glossary/Callback_function
MDN에서 정의하는 
" 콜백 함수는 전달인자로 다른 함수에 전달되는 함수입니다. 이는 일종의 루틴이나 동작을 완료하기 위해 외부 함수 내부에서 호출됩니다. "

정답은 B!
