### ISSUE TITLE
정말로 transform 속성은 reflow 가 안일어날까?

### ISSUE THREAD

**Issue by yunseorim1116** [fe-drilling/gurren-lagann#10]
### 1. 정말로 transform 속성은 reflow 가 안일어날까?
blink 엔진을 사용하는 크롬 브라우저에서는 reflow 가 일어나지 않을 수 있지만, webkit 을 렌더링 엔진으로 사용하는 사파리에서는 다릅니다.

참고 자료 : https://ssocoit.tistory.com/258

### 2. 또한 큐의 실행 우선순서가 마이크로 / raq / 매크로  라고 알고 있는 분들이 많겠지만 사파리 엔진에서는 조금 다른 결과가 출력이 됩니다.

```
setTimeout(() => {
  console.log("setTimeout-1");
});
requestAnimationFrame(() => {
  console.log("requestAnimationFrame-1");
});
queueMicrotask(() => {
  console.log("queueMicrotask-1");
});
setTimeout(() => {
  console.log("setTimeout-2");
}, 0);
requestAnimationFrame(() => {
  console.log("requestAnimationFrame-2");
});

```
**[ 사파리 console 출력값 참고 ]**

![image](https://github.com/fe-drilling/gurren-lagann/assets/94429667/9947dbd4-30c7-418d-b983-341701800bb2)

이벤트루프는 렌더링 엔진에 포함되어 있습니다. 각 브라우저마자 다른 렌더링 엔진을 사용하기 때문에 이런 결과가 출력이 되는 것이 아닐까 예상해보았습니다.

### 3. 마이크로가 우선순위가 높다는 얘기는, 마이크로가 먼저 실행이 된다는 뜻이 아닙니다.
![image](https://github.com/fe-drilling/gurren-lagann/assets/94429667/85dd2db7-d4d2-445b-8685-e78aaf4b89eb)

정확히 먼저 실행 되는 것은 가장 오래된 매크로태스크 큐에 있는 작업입니다.

참고자료 : https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model

**Comment by yunseorim1116** [comment]
크롬 v8 기준으로 문서와 블로그 정보들이 작성되어 있지만 우리는 더 나아가서 렌더링 엔진마다 어떤 차이가 있는지 알아두는 것도 좋을 것 같습니다.

**Comment by ainochi-kor** [comment]
마이크로가 먼저 실행되지 않는다는 내용이 좋네요! 
그럼 저기 예제에 있는 "Start"와 "End"가 가장 오래된 태스크인가요?
