### ISSUE TITLE
보다 상세한 DNS 동작과정을 알아봅시다!

### ISSUE THREAD

**Issue by havenothorn** [fe-drilling/gurren-lagann#12]
### 제가 배운 DNS 동작과정은 굉장히 많은 생략이 되어있었습니다.

 그리하여 깊게 알아보았습니다. 🤔

1. 웹 브라우저에 URL을 입력한다. **DNS 쿼리 발생**
브라우저는 OS 내부 소켓 라이브러리의 리졸버 함수 호출.
➡️ 어플리케이션에서 호출되어 도메인 명을 IP 주소로 변환하는 리졸버 **스텁 리졸버 Stub resolver**
2. 스텁 리졸버는 요청을 받으면 먼저 캐시를 검색하여 레코드가 있는지 확인한다. OS캐시, 라우터 캐시를 확인하고, 이후 **HOSTS 파일**까지 확인하여 찾아본다.
3. HOSTS 파일에 정보가 없을 경우 **로컬 DNS 서버**에 DNS 쿼리 도착, 도메인 해석 요청.
➡️ 로컬 DNS에서 도메인 해석을 담당하는 리졸버 **Full resolver 풀 리졸버**
스텁 리졸버가 로컬 DNS로 요청하는 과정을 **재귀 질의 Recursive Query**라 한다.
보통 로컬 DNS는 KT, SK 브로드 밴드와 같은 ISP 업체에서 관리하며 이외에 Google Public DNS, Quad9, Cloudflare 등 다양한 퍼블릭 DNS가 있다.
4. 풀 리졸버는 루트 DNS에게 요청하기 전에 본인이 가지고 있는 Resource Recordset 정보를 참조하여 응답하게 되고, 정보가 없다면 Root Hint 파일을 참조하여 계층적 순서로 **반복 질의 Iterative Query**를 한다. 🔽
5. 루트 DNS 서버에게 하위 계층에 해당되는 TLD 부터, 레지스트리에서 관리하는 네임서버까지 도메인에 대한 정보를 요청하게 되고, 이 과정을 토대로 요청 도메인에 대한 주소 정보를 전달 받는다.
6. 로컬 DNS에서는 이 정보를 재사용하기 위해 결과를 캐싱한다.

----
동작 과정외에 DNS 내부 구성 요소 등에 대한 정보는 제 블로그에 포스팅 하였습니다.
[[DNS Domain Name System을 깊게 알아보자]](https://nami-socket.tistory.com/26)

보다 상세히 알 수 있었던 출처도 납깁니다.
[[DNS cache]](https://www.catchpoint.com/blog/dns-cache)
[[브라우저에서 요청한 도메인을 DNS 를 통해 해석되는 절차에 대해서 알아보자]](https://medium.com/cloudvillains/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EC%97%90%EC%84%9C-%EC%9A%94%EC%B2%AD%ED%95%9C-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%9D%84-dns-%EB%A5%BC-%ED%86%B5%ED%95%B4-%ED%95%B4%EC%84%9D%EB%90%98%EB%8A%94-%EC%A0%88%EC%B0%A8%EB%A5%BC-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90-a3cce5307840)
[[RFC 1034 Internet Standard]](https://datatracker.ietf.org/doc/html/rfc1034)

**Comment by ainochi-kor** [comment]
예전에 C#으로 만든 프로덕트에서 외부 DB 연결할 때, host 파일을 이용한 기억이 나네요!
간단하게 정리해주셔서 좋네요!
