### ISSUE TITLE
async await 크롬 개발자 도구 조심하세요

### ISSUE THREAD

**Issue by jinseoIT** [fe-drilling/gurren-lagann#2]
await을 사용하기 위해서는 function 앞에 async를 선언해야 합니다.
```javascript
async function getApi () {
     return await api.getList();
}
```
async로 감싸지 않는다면 아래와 같은 오류가 나옵니다.
![](https://velog.velcdn.com/images/radin/post/11e3fdc9-1dfc-4779-8a16-4cdef430f8df/image.png)

하지만 우리의 크롬 개발자 도구는 async를 감싸지 않아도 await을 지원해 줍니다.(헷갈리지 않게 조심하세요)
아래 링크 참고
Chrome [added support for it](https://developers.google.com/web/updates/2017/08/devtools-release-notes#await) to the dev tools.

**Comment by ainochi-kor** [comment]
와 이건 처음 알았는데, 아래를 실행시키면 왜 3과 4가 왜 안될까요
```
console.log("1");
await new Promise(() => {console.log("2")})
console.log("3");
console.log("4");
```

**Comment by yunseorim1116** [comment]
이건 크롬 디벨롭퍼 디버깅 툴과 상관 없는 문제로  Promise 내부에서 resolve 나 reject 를 호출하지 않았기 때문에 pending 상태에 머물러 있기 때문에 생긴 문제인 것 같습니다. 해당 로직을 즉시 실행 함수에 넣고 실행해  디버깅 해보니 Promise {<pending>}`  라고 나와 힌트를 얻을 수 있었네요.^__^

```
  console.log("1");
  await new Promise((resolve) => {
    console.log("2");
    resolve();
  });
  console.log("3");
  console.log("4");

```
이런식으로 promise 안에 resolve() 코드를 삽입해 실행시켜 주시면 해결 됩니다. 

```
(async () => {
  console.log("1");
  await new Promise((resolve) => {
    console.log("2");
    resolve();
  });
  console.log("3");
  console.log("4");
})();
```
이하 동문입니다!

**Comment by ainochi-kor** [comment]
https://github.com/tc39/proposal-top-level-await
