### ISSUE TITLE
0.1 + 0.2 === 0.3 이 false 소수점 계산 오류 해결 방법

### ISSUE THREAD

**Issue by jinseoIT** [fe-drilling/gurren-lagann#4]
```javascript
0.1 + 0.2 === 0.3  // false
// 0.30000000000000004
```
왜 이렇게 나올까여?

-  10진법으로 계산하는것이 아니라 2진법으로 계산한다는 것은 알고 계실겁니다. 몇몇 소수의 경우에는 10진법을 2진법으로 변환할 때 무한소수가 되어버리는데, 유한한 컴퓨터의 자원을 활용하는 프로그램은 당연히 저장공간의 한계로 인해 결국 무한 소수를 유한한 수로 바꾸게 되고, 그 과정에서 나타나는 미세한 오차가 계산의 오류를 범하게 하는 것입니다.

- 좀 더 자세히 알아보자면, 숫자는 내부적으로 64비트 형식 IEEE-754으로 표현되기 때문에 숫자를 저장하려면 정확히 64비트가 필요합니다. 64비트 중 52비트는 숫자를 저장하는 데 사용되고, 11비트는 소수점 위치를(정수는 0), 1비트는 부호를 저장하는 데 사용됩니다. 그런데 너무 큰 수는 표현하는 데 64비트를 초과하기 때문에 Infinity로 처리 됩니다. 이 사실을 먼저 알고서 소수점 오류를 이해해야 합니다.

### 1.  toFixed()메소드
```javascript
console.log(Number(0.1 + 0.2).toFixed(2)); // 0.3
console.log(+(0.1 + 0.2).toFixed(2)); // 0.3
```
### Math객체 메소드 활용
정수로 결과값이 나와야할 경우에는 설계자의 요구에 따라 Math.round() / Math.ceil() / Math.trunc() 등을 이용하기도 합니다.

출처
[소수점 계산 오류 해결 방법](https://chiefcoder.tistory.com/13)

**Comment by ainochi-kor** [comment]
https://poiemaweb.com/js-number

```js
console.log(0.1 + 0.2);        // 0.30000000000000004
console.log(0.1 + 0.2 == 0.3); // false!!!

function isEqual(a, b){
  // Math.abs는 절댓값을 반환한다.
  // 즉 a와 b의 차이가 JavaScript에서 표현할 수 있는 가장 작은 수인 Number.EPSILON보다 작으면 같은 수로 인정할 수 있다.
  return Math.abs(a - b) < Number.EPSILON;
}

console.log(isEqual(0.1 + 0.2, 0.3));
```
